<?php

namespace Idrolab\JobeetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
  public function getAllCategories(){

    $qb = $this->createQueryBuilder('c')
       ->leftJoin('c.jobs', 'j');
    
    return $qb->getQuery()->getResult();
  }
  public function getAllCategoriesWithJobs(){

    $qb = $this->createQueryBuilder('c')
       ->Join('c.jobs', 'j');

    return $qb->getQuery()->getResult();
  }
}
